//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN
    {
        public string id_detalle_orden { get; set; }
        public decimal cantidad { get; set; }
        public string u_medida { get; set; }
        public string id_orden { get; set; }
        public string id_insumo { get; set; }
        public string estado { get; set; }
    
        public virtual ESTADO_ORDEN ESTADO_ORDEN { get; set; }
        public virtual INSUMO INSUMO { get; set; }
        public virtual ORDEN ORDEN { get; set; }
    }
}
