//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMO()
        {
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public string id_insumo { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<System.DateTime> fecha_abastecimiento { get; set; }
        public string id_prov { get; set; }
        public string id_marca { get; set; }
        public string id_categoria { get; set; }
    
        public virtual CATEGORIA_INSUMO CATEGORIA_INSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
