//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public string id_preparacion { get; set; }
        public string id_insumo { get; set; }
        public Nullable<decimal> porcion { get; set; }
        public string u_medida { get; set; }
        public string id_receta { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual PREPARACION PREPARACION { get; set; }
    }
}
