//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public string id_reserva { get; set; }
        public string nombre_cliente { get; set; }
        public string id_mesa { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
    
        public virtual ESTADO_RESERVA ESTADO_RESERVA { get; set; }
        public virtual MESA MESA { get; set; }
    }
}
