//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante_preparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurante_preparacion()
        {
            this.Restaurante_pedido = new HashSet<Restaurante_pedido>();
            this.Restaurante_receta = new HashSet<Restaurante_receta>();
        }
    
        public long id { get; set; }
        public string nombre_receta { get; set; }
        public Nullable<int> precio { get; set; }
        public string img_preparacion { get; set; }
        public string modo_prep { get; set; }
        public Nullable<long> id_categoria { get; set; }
        public Nullable<long> minuto_prep { get; set; }
    
        public virtual Restaurante_categoria Restaurante_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante_pedido> Restaurante_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante_receta> Restaurante_receta { get; set; }
    }
}
