//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante_insumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurante_insumo()
        {
            this.Restaurante_detalleorden = new HashSet<Restaurante_detalleorden>();
            this.Restaurante_receta = new HashSet<Restaurante_receta>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> fecha_abastecimiento { get; set; }
        public long id_categoria { get; set; }
        public Nullable<long> id_marca { get; set; }
        public Nullable<long> id_prov { get; set; }
    
        public virtual Restaurante_categoriainsumo Restaurante_categoriainsumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante_detalleorden> Restaurante_detalleorden { get; set; }
        public virtual Restaurante_marca Restaurante_marca { get; set; }
        public virtual Restaurante_proveedor Restaurante_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante_receta> Restaurante_receta { get; set; }
    }
}
