//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante_mesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurante_mesa()
        {
            this.Restaurante_atencion = new HashSet<Restaurante_atencion>();
            this.Restaurante_reserva = new HashSet<Restaurante_reserva>();
        }
    
        public long id { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<long> estado { get; set; }
        public Nullable<long> id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante_atencion> Restaurante_atencion { get; set; }
        public virtual Restaurante_estadomesa Restaurante_estadomesa { get; set; }
        public virtual Restaurante_usuario Restaurante_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante_reserva> Restaurante_reserva { get; set; }
    }
}
