//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante_boleta
    {
        public long id { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<int> valor_total { get; set; }
        public Nullable<long> id_atencion { get; set; }
        public Nullable<long> id_medio_de_pago { get; set; }
    
        public virtual Restaurante_atencion Restaurante_atencion { get; set; }
        public virtual Restaurante_mediodepago Restaurante_mediodepago { get; set; }
    }
}
