//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auth_user> auth_user { get; set; }
        public virtual DbSet<Restaurante_atencion> Restaurante_atencion { get; set; }
        public virtual DbSet<Restaurante_boleta> Restaurante_boleta { get; set; }
        public virtual DbSet<Restaurante_categoria> Restaurante_categoria { get; set; }
        public virtual DbSet<Restaurante_categoriainsumo> Restaurante_categoriainsumo { get; set; }
        public virtual DbSet<Restaurante_detalleorden> Restaurante_detalleorden { get; set; }
        public virtual DbSet<Restaurante_estadomesa> Restaurante_estadomesa { get; set; }
        public virtual DbSet<Restaurante_estadoorden> Restaurante_estadoorden { get; set; }
        public virtual DbSet<Restaurante_estadoreserva> Restaurante_estadoreserva { get; set; }
        public virtual DbSet<Restaurante_insumo> Restaurante_insumo { get; set; }
        public virtual DbSet<Restaurante_marca> Restaurante_marca { get; set; }
        public virtual DbSet<Restaurante_mediodepago> Restaurante_mediodepago { get; set; }
        public virtual DbSet<Restaurante_mesa> Restaurante_mesa { get; set; }
        public virtual DbSet<Restaurante_orden> Restaurante_orden { get; set; }
        public virtual DbSet<Restaurante_pedido> Restaurante_pedido { get; set; }
        public virtual DbSet<Restaurante_preparacion> Restaurante_preparacion { get; set; }
        public virtual DbSet<Restaurante_proveedor> Restaurante_proveedor { get; set; }
        public virtual DbSet<Restaurante_receta> Restaurante_receta { get; set; }
        public virtual DbSet<Restaurante_reserva> Restaurante_reserva { get; set; }
        public virtual DbSet<Restaurante_rol> Restaurante_rol { get; set; }
        public virtual DbSet<Restaurante_usuario> Restaurante_usuario { get; set; }
    
        public virtual ObjectResult<SP_listarAtencion_Result> SP_listarAtencion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarAtencion_Result>("SP_listarAtencion");
        }
    
        public virtual ObjectResult<SP_listarBoleta_Result> SP_listarBoleta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarBoleta_Result>("SP_listarBoleta");
        }
    
        public virtual ObjectResult<SP_listarCategoria_Result> SP_listarCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarCategoria_Result>("SP_listarCategoria");
        }
    
        public virtual ObjectResult<SP_listarCategoriaInsumo_Result> SP_listarCategoriaInsumo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarCategoriaInsumo_Result>("SP_listarCategoriaInsumo");
        }
    
        public virtual ObjectResult<SP_listarDetalleOrden_Result> SP_listarDetalleOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarDetalleOrden_Result>("SP_listarDetalleOrden");
        }
    
        public virtual ObjectResult<SP_listarEstadoMesa_Result> SP_listarEstadoMesa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarEstadoMesa_Result>("SP_listarEstadoMesa");
        }
    
        public virtual ObjectResult<SP_listarEstadoOrden_Result> SP_listarEstadoOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarEstadoOrden_Result>("SP_listarEstadoOrden");
        }
    
        public virtual ObjectResult<SP_listarEstadoReserva_Result> SP_listarEstadoReserva()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarEstadoReserva_Result>("SP_listarEstadoReserva");
        }
    
        public virtual ObjectResult<SP_listarInsumo_Result> SP_listarInsumo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarInsumo_Result>("SP_listarInsumo");
        }
    
        public virtual ObjectResult<SP_listarMarca_Result> SP_listarMarca()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarMarca_Result>("SP_listarMarca");
        }
    
        public virtual ObjectResult<SP_listarMedioPago_Result> SP_listarMedioPago()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarMedioPago_Result>("SP_listarMedioPago");
        }
    
        public virtual ObjectResult<SP_listarMesa_Result> SP_listarMesa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarMesa_Result>("SP_listarMesa");
        }
    
        public virtual ObjectResult<SP_listarOrden_Result> SP_listarOrden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarOrden_Result>("SP_listarOrden");
        }
    
        public virtual ObjectResult<SP_listarPedido_Result> SP_listarPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarPedido_Result>("SP_listarPedido");
        }
    
        public virtual ObjectResult<SP_listarPreparacion_Result> SP_listarPreparacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarPreparacion_Result>("SP_listarPreparacion");
        }
    
        public virtual ObjectResult<SP_listarProveedor_Result> SP_listarProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarProveedor_Result>("SP_listarProveedor");
        }
    
        public virtual ObjectResult<SP_listarReceta_Result> SP_listarReceta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarReceta_Result>("SP_listarReceta");
        }
    
        public virtual ObjectResult<SP_listarReserva_Result> SP_listarReserva()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarReserva_Result>("SP_listarReserva");
        }
    
        public virtual ObjectResult<SP_listarRol_Result> SP_listarRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarRol_Result>("SP_listarRol");
        }
    
        public virtual ObjectResult<SP_listarUsuario_Result> SP_listarUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_listarUsuario_Result>("SP_listarUsuario");
        }
    }
}
