//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante_pedido
    {
        public long id { get; set; }
        public string id_mesa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<bool> entregado { get; set; }
        public long id_atencion { get; set; }
        public Nullable<long> id_preparacion { get; set; }
    
        public virtual Restaurante_atencion Restaurante_atencion { get; set; }
        public virtual Restaurante_preparacion Restaurante_preparacion { get; set; }
    }
}
