//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante_receta
    {
        public long id { get; set; }
        public Nullable<int> porcion { get; set; }
        public string u_medida { get; set; }
        public Nullable<long> id_insumo { get; set; }
        public Nullable<long> id_preparacion { get; set; }
    
        public virtual Restaurante_insumo Restaurante_insumo { get; set; }
        public virtual Restaurante_preparacion Restaurante_preparacion { get; set; }
    }
}
